name: "Build & Test"

on:
  merge_group: {}
  pull_request:
    paths-ignore:
      - docs/**
      - theme/**
      - po/**
      - book.toml
      - .github/workflows/docs.yaml
  push:
    branches:
      - main
    paths-ignore:
      - docs/**
      - theme/**
      - po/**
      - book.toml
      - .github/workflows/docs.yaml
  workflow_dispatch: {}

permissions: {}

jobs:

  setup-tmate:
    name: Debug with tmate
    runs-on: ubuntu-latest
    outputs:
      ssh-command: ${{ steps.tmate.outputs.ssh-command }}
      ssh-address: ${{ steps.tmate.outputs.ssh-address }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup tmate session
        id: tmate
        uses: mxschmitt/action-tmate@v3
        with:
          detached: true

  notify-ntfy:
    name: Notify via ntfy
    needs: setup-tmate
    runs-on: ubuntu-latest
    steps:
      - name: Send ntfy notification
        env:
          SSH_COMMAND: ${{ needs.setup-tmate.outputs.ssh-command }}
          SSH_ADDRESS: ${{ needs.setup-tmate.outputs.ssh-address }}
        run: |
          curl -H "Title: GitHub Actions Debug Session" \
               -H "Priority: high" \
               -d "SSH command:
$SSH_COMMAND

SSH address:
$SSH_ADDRESS" \
               https://ntfy.sh/tkwosbc8amebwhao7swvooq

  build:
    name: Build
    needs:
      - setup-tmate
      - notify-ntfy
    runs-on: ubuntu-latest

    outputs:
      distro: ${{ steps.distro_check.outputs.distro }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          submodules: recursive

      - name: Set up QEMU Emulation
        uses: docker/setup-qemu-action@v3
        with:
          image: tonistiigi/binfmt:latest

      - name: Build
        uses: devcontainers/ci@v0.3
        with:
          push: "never"
          runCmd: |
            set -euo pipefail
            make deb

      - name: Workaround actions/upload-artifact#176
        id: artifacts_path
        run: echo "artifacts_path=$(realpath ..)" >> "$GITHUB_OUTPUT"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}
          path: ${{ steps.artifacts_path.outputs.artifacts_path }}/*.deb

      - name: Check if the latest version is releasable
        id: distro_check
        shell: bash
        run: |
          version="$(dpkg-parsechangelog -S Version)"
          version="${version//\~/.}"

          if git tag -l "$version" | grep -q .
          then
              echo "distro=UNRELEASED" >> "$GITHUB_OUTPUT"
          else
              echo "distro=$(dpkg-parsechangelog -S Distribution)" >> "$GITHUB_OUTPUT"
          fi

      - name: Wait
        run: |
          while true; do
            sleep 5
            echo testing
          done
